/**
 * One test per rule id of the transition table, plus the generated truth table
 * Role × Status × Action, diffed against the committed file (docs gate "Policy-Wahrheitstabelle").
 */
import { describe, expect, it } from 'vitest';
import { TRANSITIONS, resolveTransition } from '../transitions.js';
import { can } from '../api.js';
import { PERMISSIONS, QUESTION_STATUSES, type QuestionRecord, type Role, type Permission } from '../types.js';
import { ROLE_PERMISSIONS } from '../permissions.js';

const ROLES = Object.keys(ROLE_PERMISSIONS) as Role[];

function question(overrides: Partial<QuestionRecord> = {}): QuestionRecord {
  return {
    id: 'q1',
    number: 'F-0001',
    contributionId: 'c1',
    speakerId: 's1',
    text: 'Wie hoch war die Ausschüttungsquote?',
    status: 'captured',
    answers: [],
    version: 1,
    createdAt: '2027-04-20T08:00:00.000Z',
    updatedAt: '2027-04-20T08:00:00.000Z',
    ...overrides,
  };
}

describe('transition table', () => {
  it('has unique rule ids', () => {
    const ids = TRANSITIONS.map((t) => t.ruleId);
    expect(new Set(ids).size).toBe(ids.length);
  });

  for (const t of TRANSITIONS) {
    it(`${t.ruleId}: ${t.action} from [${t.from.join(', ')}] — ${t.description}`, () => {
      // A representative question that satisfies every guard of this row.
      const base = question({
        status: t.from[0]!,
        track: t.ruleId === 'R-TRANS-08' ? 'podium' : 'expert_track',
        answers: [{ version: 1, text: 'Antwort', createdAt: '2027-04-20T09:00:00.000Z', createdBy: { id: 'e', role: 'expert' } }],
      });
      const payload = t.action === 'question.approve' ? { answerVersion: 1 } : t.action === 'question.merge' ? { intoQuestionId: 'q2' } : undefined;
      const r = resolveTransition(base, t.action, payload);
      expect(r.ok).toBe(true);
      if (r.ok) expect(r.transition.ruleId).toBe(t.ruleId);
      // And it is forbidden from a status the row does not list.
      const other = QUESTION_STATUSES.find((s) => !t.from.includes(s) && !['closed', 'withdrawn', 'merged'].includes(s));
      if (other) {
        const otherRows = TRANSITIONS.filter((x) => x.action === t.action && x.from.includes(other));
        if (otherRows.length === 0) {
          expect(resolveTransition(question({ ...base, status: other }), t.action, payload).ok).toBe(false);
        }
      }
    });
  }

  it('R-TRANS-00: terminal statuses accept no action', () => {
    for (const s of ['closed', 'withdrawn', 'merged'] as const) {
      for (const p of PERMISSIONS) {
        expect(resolveTransition(question({ status: s }), p).ok).toBe(false);
      }
    }
  });

  it('R-GUARD-04: approval must name the latest answer version', () => {
    const q = question({
      status: 'in_review',
      track: 'expert_track',
      answers: [
        { version: 1, text: 'v1', createdAt: '2027-04-20T09:00:00.000Z', createdBy: { id: 'e', role: 'expert' } },
        { version: 2, text: 'v2', createdAt: '2027-04-20T09:10:00.000Z', createdBy: { id: 'e', role: 'expert' } },
      ],
    });
    expect(resolveTransition(q, 'question.approve', { answerVersion: 1 }).ok).toBe(false);
    expect(resolveTransition(q, 'question.approve', { answerVersion: 2 }).ok).toBe(true);
  });

  it('R-TRANS-06: a returned podium question goes back to classified, a text question to answer_drafted', () => {
    const podium = resolveTransition(question({ status: 'staged', track: 'podium' }), 'question.return', { reason: 'x' });
    const expert = resolveTransition(question({ status: 'staged', track: 'expert_track' }), 'question.return', { reason: 'x' });
    expect(podium.ok && podium.to).toBe('classified');
    expect(expert.ok && expert.to).toBe('answer_drafted');
  });
});

describe('policy truth table (Role × Status × Action)', () => {
  const actions = PERMISSIONS.filter((p) => p.startsWith('question.') || p === 'answer.draft') as Permission[];
  it('matches the committed table — any change must be reviewed', async () => {
    const lines: string[] = [
      '# Policy truth table — Role × Status × Action',
      '',
      'Generated by `packages/domain/src/__tests__/transitions.test.ts`. A diff here is a rights change and',
      'needs an explicit decision (docs/rollen-und-rechtekonzept.md). Representative question: expert track,',
      'one answer version; podium-track rows are marked separately.',
      '',
      '| Role | Status | ' + actions.map((a) => a.replace('question.', 'q.')).join(' | ') + ' |',
      '|---|---|' + actions.map(() => '---').join('|') + '|',
    ];
    for (const role of ROLES) {
      for (const status of QUESTION_STATUSES) {
        for (const track of ['expert_track', 'podium'] as const) {
          const q = question({
            status,
            track,
            answers: track === 'podium' ? [] : [{ version: 1, text: 'v1', createdAt: '2027-04-20T09:00:00.000Z', createdBy: { id: 'e', role: 'expert' } }],
          });
          const cells = actions.map((a) => {
            const payload = a === 'question.approve' ? { answerVersion: 1 } : a === 'question.merge' ? { intoQuestionId: 'other' } : undefined;
            return can({ id: 'x', role }, a, q, payload).allow ? '✓' : '·';
          });
          lines.push(`| ${role} | ${status}${track === 'podium' ? ' (podium)' : ''} | ${cells.join(' | ')} |`);
        }
      }
    }
    await expect(lines.join('\n') + '\n').toMatchFileSnapshot('../../policy-truth-table.md');
  });

  it('deny by default: an unknown role has no permissions', () => {
    const d = can({ id: 'x', role: 'nobody' as Role }, 'question.read');
    expect(d.allow).toBe(false);
    if (!d.allow) expect(d.ruleId).toBe('R-PERM-01');
  });
});
