/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meeting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current meeting */
        get: operations["getMeeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agenda-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agenda items (Tagesordnungspunkte) */
        get: operations["listAgendaItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List answering units (Fachbereiche) */
        get: operations["listUnits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List speakers (Wortmeldeliste), ordered by round and position */
        get: operations["listSpeakers"];
        put?: never;
        /** Register a speaker (Wortmeldung aufnehmen) */
        post: operations["registerSpeaker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the order of speakers within a round (Reihenfolge ändern) */
        put: operations["reorderSpeakers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speakers/{speakerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speakerId: components["parameters"]["SpeakerId"];
            };
            cookie?: never;
        };
        /** Get a speaker */
        get: operations["getSpeaker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change speaker status or round (Redner aufrufen, beenden, zurückziehen) */
        patch: operations["updateSpeaker"];
        trace?: never;
    };
    "/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List speeches (Redebeiträge) */
        get: operations["listContributions"];
        put?: never;
        /**
         * Capture a speech (Redebeitrag erfassen)
         * @description Creates the immutable text of a speech. Questions are then atomised out of it with `captureQuestions`. Later, transcript segments arrive through the ingest interface and become contributions the same way.
         */
        post: operations["captureContribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributions/{contributionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributionId: components["parameters"]["ContributionId"];
            };
            cookie?: never;
        };
        /** Get a speech with its coverage (Restabdeckung) */
        get: operations["getContribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contributions/{contributionId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributionId: components["parameters"]["ContributionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomise a speech into individual questions (Einzelfragen erfassen) */
        post: operations["captureQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List questions with filters */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        /** Get a question with its answer versions and allowed actions */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        /** Full event history of a question (Vorgangshistorie) */
        get: operations["getQuestionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify a question (Klassifizieren) — answer track, agenda item, stage assignment */
        post: operations["classifyQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a question to an answering unit (Zuweisen an Fachbereich) */
        post: operations["assignQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an answer version (Antwortentwurf)
         * @description Every call creates a new, immutable answer version. If the question was already approved, the approval is bound to the earlier version and the question falls back to `answer_drafted`.
         */
        post: operations["draftAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/review-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the current answer version for legal clearing (Zur Prüfung geben) */
        post: operations["submitForReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve an answer version (Freigeben) — the approval is bound to the version */
        post: operations["approveQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return a question for rework (Zurückgeben) from review, staging or the podium */
        post: operations["returnQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/staging": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put an approved question on the podium queue (Auf die Bühne legen) */
        post: operations["stageQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the answer as read out on the podium (Vorgelesen) */
        post: operations["deliverQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/closure": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a delivered question (Abschließen) */
        post: operations["closeQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw a question (Zurückgezogen) — e.g. the shareholder withdrew it */
        post: operations["withdrawQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge a duplicate into another question (Zusammenführen) */
        post: operations["mergeQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Podium view (Bühne) — current question, queue, counters */
        get: operations["getStage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Append-only event feed. Poll with `after` = last seen sequence number. */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace all data with a synthetic corpus (demo only) */
        post: operations["seedDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details, extended with the rule id that produced the decision. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Rule id from the domain rule tables */
            ruleId?: string;
        };
        /**
         * @description Roles are only a bundle of permissions (see docs/rollen-und-rechtekonzept.md). The interface never branches on a role name; it reads `_actions`.
         * @enum {string}
         */
        Role: "moderation" | "capture" | "expert" | "legal" | "approver" | "podium" | "admin" | "observer";
        Actor: {
            id: string;
            role: components["schemas"]["Role"];
            displayName?: string;
        };
        /**
         * @description Permission identifiers, identical to the domain permission list.
         * @enum {string}
         */
        Action: "speaker.register" | "speaker.reorder" | "speaker.update" | "contribution.capture" | "question.capture" | "question.classify" | "question.assign" | "answer.draft" | "question.submit_review" | "question.approve" | "question.return" | "question.stage" | "question.deliver" | "question.close" | "question.withdraw" | "question.merge" | "question.read" | "demo.seed";
        Meeting: {
            id: string;
            /** @example Ordentliche Hauptversammlung 2027 */
            title: string;
            legalEntity?: string;
            /** Format: date */
            date: string;
            /** @enum {string} */
            status: "preparation" | "running" | "closed";
            currentRound: number;
            /** @description Aggregate counters for the header and the podium */
            counts: {
                speakers?: number;
                questions?: number;
                open?: number;
                staged?: number;
                delivered?: number;
            };
        };
        AgendaItem: {
            id: string;
            number: number;
            title: string;
        };
        Unit: {
            id: string;
            name: string;
            shortName?: string;
        };
        /** @enum {string} */
        SpeakerStatus: "waiting" | "speaking" | "finished" | "withdrawn";
        Speaker: {
            id: string;
            /** @description Running number of the request to speak */
            number: number;
            /** @description Pseudonym in the demo; real name only via the register interface */
            displayName: string;
            organisation?: string;
            /** @enum {string} */
            kind: "shareholder" | "proxy" | "association";
            round: number;
            position: number;
            status: components["schemas"]["SpeakerStatus"];
            requestedMinutes?: number;
            /** Format: date-time */
            speakingStartedAt?: string;
            /** Format: date-time */
            speakingEndedAt?: string;
            questionCount?: number;
            version: number;
            _actions?: components["schemas"]["Action"][];
        };
        SpeakerRegistration: {
            displayName: string;
            organisation?: string;
            /** @enum {string} */
            kind: "shareholder" | "proxy" | "association";
            round?: number;
            requestedMinutes?: number;
        };
        SpeakerUpdate: {
            status?: components["schemas"]["SpeakerStatus"];
            round?: number;
            requestedMinutes?: number;
        };
        /** @description Character offsets into the contribution text, half-open interval */
        TextSpan: {
            start: number;
            end: number;
        };
        Contribution: {
            id: string;
            speakerId: string;
            text: string;
            /** Format: date-time */
            capturedAt: string;
            /**
             * @default manual
             * @enum {string}
             */
            source: "manual" | "transcript";
            questionIds: string[];
            /** @description How much of the text is covered by captured questions (Restabdeckung) */
            coverage: {
                coveredRatio: number;
                uncovered: components["schemas"]["TextSpan"][];
            };
        };
        ContributionCapture: {
            speakerId: string;
            text: string;
            /** @enum {string} */
            source?: "manual" | "transcript";
        };
        /**
         * @description The three answer tracks (Antwortpfade). `podium` = free answer by the board (Pfad A), `fast_track` = reference to an existing publication (Pfad B), `expert_track` = specialist answer followed by legal clearing (Pfad C).
         * @enum {string}
         */
        Track: "podium" | "fast_track" | "expert_track";
        /**
         * @description Who answers on the podium (Bühnenzuordnung)
         * @enum {string}
         */
        StageAssignment: "supervisory_board_chair" | "ceo" | "cfo" | "board_member";
        /**
         * @description Workflow status. Transitions are defined as data in the domain transition table; the interface never hard-codes them.
         * @enum {string}
         */
        QuestionStatus: "captured" | "classified" | "assigned" | "answer_drafted" | "in_review" | "approved" | "staged" | "delivered" | "closed" | "withdrawn" | "merged";
        AnswerVersion: {
            version: number;
            text: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["Actor"];
            /** @description References the answer relies on (publication, catalogue entry, document) */
            sources?: string[];
        };
        Approval: {
            answerVersion: number;
            /** Format: date-time */
            approvedAt: string;
            approvedBy: components["schemas"]["Actor"];
        };
        Question: {
            id: string;
            /** @example F-0417 */
            number: string;
            contributionId: string;
            speakerId: string;
            speakerDisplayName?: string;
            text: string;
            span?: components["schemas"]["TextSpan"];
            status: components["schemas"]["QuestionStatus"];
            track?: components["schemas"]["Track"];
            agendaItemId?: string;
            stageAssignment?: components["schemas"]["StageAssignment"];
            unitId?: string;
            answers: components["schemas"]["AnswerVersion"][];
            approval?: components["schemas"]["Approval"];
            returnReason?: string;
            stagePosition?: number;
            /** Format: date-time */
            deliveredAt?: string;
            mergedIntoId?: string;
            /** @description Optimistic-locking counter */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Actions the calling actor may perform on this question right now */
            _actions: components["schemas"]["Action"][];
        };
        QuestionCapture: {
            text: string;
            span?: components["schemas"]["TextSpan"];
        };
        Classification: {
            track: components["schemas"]["Track"];
            agendaItemId?: string;
            stageAssignment?: components["schemas"]["StageAssignment"];
        };
        AnswerDraft: {
            text: string;
            sources?: string[];
        };
        StageView: {
            current: components["schemas"]["Question"] | null;
            queue: components["schemas"]["Question"][];
            deliveredCount: number;
            openCount: number;
        };
        /** @description One immutable fact. The sequence number is global and gap-free. */
        Event: {
            seq: number;
            id: string;
            /** @enum {string} */
            type: "MeetingCreated" | "SpeakerRegistered" | "SpeakersReordered" | "SpeakerUpdated" | "ContributionCaptured" | "QuestionCaptured" | "QuestionClassified" | "QuestionAssigned" | "AnswerDrafted" | "QuestionSubmittedForReview" | "QuestionApproved" | "QuestionReturned" | "QuestionStaged" | "QuestionDelivered" | "QuestionClosed" | "QuestionWithdrawn" | "QuestionMerged";
            /** Format: date-time */
            at: string;
            actor: components["schemas"]["Actor"];
            /** @description Id of the aggregate the event belongs to */
            subjectId?: string;
            payload: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Updated question with new ETag and current `_actions` */
        QuestionUpdated: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Question"];
            };
        };
        /** @description The actor may not perform this action (deny reason in `detail`, rule id in `ruleId`) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The transition is not allowed from the current status */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match did not match the current ETag */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation failed */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key. A replay with the same key returns the original result. */
        IdempotencyKey: string;
        /** @description ETag of the resource the client last saw. Mismatch yields 412. */
        IfMatch: string;
        SpeakerId: string;
        ContributionId: string;
        QuestionId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Opaque version tag, changes with every write. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
        };
    };
    listAgendaItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaItem"][];
                };
            };
        };
    };
    listUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"][];
                };
            };
        };
    };
    listSpeakers: {
        parameters: {
            query?: {
                round?: number;
                status?: components["schemas"]["SpeakerStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"][];
                };
            };
        };
    };
    registerSpeaker: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerRegistration"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
        };
    };
    reorderSpeakers: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    round: number;
                    speakerIds: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"][];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getSpeaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speakerId: components["parameters"]["SpeakerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSpeaker: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                speakerId: components["parameters"]["SpeakerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listContributions: {
        parameters: {
            query?: {
                speakerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"][];
                };
            };
        };
    };
    captureContribution: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionCapture"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributionId: components["parameters"]["ContributionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    captureQuestions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                contributionId: components["parameters"]["ContributionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    questions: components["schemas"]["QuestionCapture"][];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                status?: components["schemas"]["QuestionStatus"][];
                track?: components["schemas"]["Track"];
                unitId?: string;
                speakerId?: string;
                contributionId?: string;
                agendaItemId?: string;
                /** @description Full-text search over question and answer text */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Question"][];
                        total: number;
                    };
                };
            };
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getQuestionHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    classifyQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Classification"];
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    assignQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    unitId: string;
                };
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    draftAnswer: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerDraft"];
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    submitForReview: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    approveQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    answerVersion: number;
                };
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["Unprocessable"];
        };
    };
    returnQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    stageQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    deliverQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    closeQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    withdrawQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    mergeQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key. A replay with the same key returns the original result. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description ETag of the resource the client last saw. Mismatch yields 412. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    intoQuestionId: string;
                };
            };
        };
        responses: {
            200: components["responses"]["QuestionUpdated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    getStage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageView"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Event"][];
                        lastSeq: number;
                    };
                };
            };
        };
    };
    seedDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 800 */
                    questions?: number;
                    /** @default 2027 */
                    seed?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
