/**
 * Per-request observability context (slice 033a). An `AsyncLocalStorage` carries it from the
 * outermost middleware to the places that learn something worth logging — the auth step (who),
 * the persistence step (which `seq`) and the problem mapper (`instance`, error log) — without
 * threading extra parameters through every handler.
 */
import { AsyncLocalStorage } from 'node:async_hooks';

export interface RequestContext {
  /** Generated by the service per request; a client-supplied id is never adopted. */
  readonly requestId: string;
  /** The injected clock (AGENTS.md rule 8), so the error log needs no clock of its own. */
  readonly clock: () => Date;
  subjectHash: string | null;
  seq: number | null;
  /**
   * Where the request stands for the request timeout (slice 034a): `committing` from the moment the
   * Postgres boundary sends the events and COMMIT, `timedOut` once the 408 was answered. A late boundary
   * that sees `timedOut` rolls back instead of committing.
   */
  phase: 'running' | 'committing' | 'timedOut';
  /** The access log line of this request is not written (protocol exception for repeated refusals). */
  suppressLog: boolean;
}

export const requestContext = new AsyncLocalStorage<RequestContext>();

export function currentRequest(): RequestContext | undefined {
  return requestContext.getStore();
}

/** Keeps the highest confirmed `seq` of the request (a write may append several events). */
export function noteSeq(seq: number): void {
  const context = requestContext.getStore();
  if (context !== undefined && (context.seq === null || seq > context.seq)) context.seq = seq;
}
